SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE Car;
TRUNCATE TABLE CarType;
TRUNCATE TABLE Color;
TRUNCATE TABLE ColorCarMapper;
TRUNCATE TABLE DefaultOptionData;
TRUNCATE TABLE DefaultOption;
TRUNCATE TABLE OptionCategory;
SET FOREIGN_KEY_CHECKS = 1;