SET REFERENTIAL_INTEGRITY FALSE;

INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (129, 1, 155, '69,70');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (130, 1, 165, '69,70');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (131, 1, 152, '69,70');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (132, 1, 139, '69,70');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (133, 1, 135, '69,70');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (134, 1, 164, '69,70');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (135, 1, 153, '69,70');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (136, 1, 143, '69,70');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (137, 1, 162, '69,71');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (138, 1, 148, '69,71');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (139, 1, 138, '69,71');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (140, 1, 159, '69,71');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (141, 1, 156, '69,71');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (142, 1, 150, '69,71');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (143, 1, 154, '69,71');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (144, 1, 145, '69,71');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (145, 1, 144, '69,72');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (146, 1, 157, '69,72');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (147, 1, 150, '69,72');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (148, 1, 162, '69,72');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (149, 1, 145, '69,72');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (150, 1, 155, '69,72');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (151, 1, 162, '69,72');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (152, 1, 158, '69,72');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (153, 1, 149, '69,73');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (154, 1, 145, '69,73');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (155, 1, 150, '69,73');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (156, 1, 164, '69,73');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (157, 1, 163, '69,73');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (158, 1, 152, '69,73');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (159, 1, 143, '69,73');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (160, 1, 142, '69,73');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (161, 1, 140, '69,74');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (162, 1, 138, '69,74');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (163, 1, 151, '69,74');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (164, 1, 159, '69,74');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (165, 1, 144, '69,74');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (166, 1, 139, '69,74');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (167, 1, 144, '69,74');
INSERT INTO SalesHistory (history_id, car_id, sold_count, sold_options_id) VALUES (168, 1, 149, '69,74');

INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (384, 1, 129);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (385, 3, 129);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (386, 5, 129);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (387, 1, 130);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (388, 3, 130);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (389, 6, 130);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (390, 1, 131);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (391, 4, 131);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (392, 5, 131);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (393, 1, 132);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (394, 4, 132);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (395, 6, 132);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (396, 2, 133);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (397, 3, 133);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (398, 5, 133);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (399, 2, 134);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (400, 3, 134);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (401, 6, 134);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (402, 2, 135);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (403, 4, 135);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (404, 5, 135);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (405, 2, 136);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (406, 4, 136);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (407, 6, 136);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (408, 1, 137);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (409, 3, 137);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (410, 5, 137);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (411, 1, 138);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (412, 3, 138);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (413, 6, 138);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (414, 1, 139);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (415, 4, 139);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (416, 5, 139);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (417, 1, 140);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (418, 4, 140);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (419, 6, 140);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (420, 2, 141);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (421, 3, 141);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (422, 5, 141);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (423, 2, 142);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (424, 3, 142);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (425, 6, 142);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (426, 2, 143);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (427, 4, 143);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (428, 5, 143);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (429, 2, 144);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (430, 4, 144);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (431, 6, 144);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (432, 1, 145);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (433, 3, 145);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (434, 5, 145);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (435, 1, 146);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (436, 3, 146);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (437, 6, 146);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (438, 1, 147);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (439, 4, 147);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (440, 5, 147);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (441, 1, 148);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (442, 4, 148);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (443, 6, 148);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (444, 2, 149);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (445, 3, 149);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (446, 5, 149);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (447, 2, 150);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (448, 3, 150);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (449, 6, 150);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (450, 2, 151);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (451, 4, 151);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (452, 5, 151);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (453, 2, 152);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (454, 4, 152);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (455, 6, 152);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (456, 1, 153);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (457, 3, 153);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (458, 5, 153);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (459, 1, 154);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (460, 3, 154);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (461, 6, 154);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (462, 1, 155);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (463, 4, 155);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (464, 5, 155);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (465, 1, 156);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (466, 4, 156);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (467, 6, 156);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (468, 2, 157);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (469, 3, 157);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (470, 5, 157);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (471, 2, 158);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (472, 3, 158);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (473, 6, 158);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (474, 2, 159);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (475, 4, 159);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (476, 5, 159);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (477, 2, 160);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (478, 4, 160);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (479, 6, 160);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (480, 1, 161);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (481, 3, 161);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (482, 5, 161);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (483, 1, 162);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (484, 3, 162);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (485, 6, 162);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (486, 1, 163);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (487, 4, 163);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (488, 5, 163);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (489, 1, 164);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (490, 4, 164);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (491, 6, 164);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (492, 2, 165);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (493, 3, 165);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (494, 5, 165);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (495, 2, 166);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (496, 3, 166);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (497, 6, 166);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (498, 2, 167);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (499, 4, 167);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (500, 5, 167);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (501, 2, 168);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (502, 4, 168);
INSERT INTO HistoryModelMapper (history_model_mapper_id, model_id, history_id) VALUES (503, 6, 168);
